{{- if eq .Values.database.type "postgresql" -}}
{{- if eq .Values.postgresql.enabled true -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sonarqube.postgresql.fullname" . }}
  labels:
{{ include "sonarqube.labels" . | indent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
{{- end -}}
{{- end -}}