apiVersion: v1
kind: Service
metadata:
  name: {{ template "sonarqube.fullname" . }}
  labels:
{{ include "sonarqube.labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
{{- if ne .Values.service.type "ClusterIP" }}
      targetPort: {{ .Values.service.internalPort }}
{{- end }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "sonarqube.name" . }}
    release: {{ .Release.Name }}
  {{- if eq .Values.service.type "LoadBalancer"}}
  loadBalancerSourceRanges: {{.Values.service.loadBalancerSourceRanges}}
  {{- if .Values.service.LoadBalancerIP}}
  loadBalancerIP: {{.Values.service.loadBalancerIP}}
  {{- end }}
  {{- end }}
