
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sonarqube.fullname" . }}-config
  labels:
{{ include "sonarqube.labels" . | indent 4 }}
data:
  {{- if .Values.sonarProperties }}
  sonar.properties:
{{ toYaml .Values.sonarProperties | indent 4}}
  {{- end}}
