apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sonarqube.fullname" . }}-install-plugins
  labels:
{{ include "sonarqube.labels" . | indent 4 }}
data:
  install_plugins.sh: |-
    cd /opt/sonarqube/extensions/plugins
    {{- if .Values.plugins.install }}
      {{- range $index, $val := .Values.plugins.install }}
        wget {{ $val }} --no-check-certificate
      {{- end }}
    {{- end }}
